import { NextPage } from 'next';
import React from 'react';

// eslint-disable-next-line import/no-unresolved
import Footer from '@/components/Footer';

const RootPage: NextPage = () => {
  return (
    <>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <div>
        kurakke
      </div>
      <Footer />
    </>
  );
};
export default RootPage;
